#!/bin/sh
checkflag() {
  val=$(n2hstat -x $1 | head -20 | grep "<$2>" | cut -f2 -d'>' | cut -f1 -d'<')
  [ "$val" = "1" ] && return 0
  return 1
}

if [ ! -e /var/state/n2/current/$1 ]; then
  echo "% Host not found"
  exit 1
fi
dt=$(date +%s)
exp=$((dt + 28800))
flags=""
host="$1"
curstatus=$(n2hstat -x $host | grep "<status>" | cut -f2 -d'>' | cut -f1 -d'<')
if [ "$curstatus" = "STALE" ]; then
  flags="dead "
else
  if [ "$curstatus" = "DEAD" ]; then
    flags="dead "
  fi
fi
checkflag $host rtt && flags="rtt $flags"
checkflag $host loss && flags="loss $flags"
checkflag $host load && flags="load $flags"
checkflag $host ram && flags="ram $flags"
checkflag $host swap && flags="swap $flags"
checkflag $host netin && flags="netin $flags"
checkflag $host netout && flags="netout $flags"
checkflag $host svcdown && flags="svcdown $flags"
checkflag $host diskio && flags="diskio $flags"
checkflag $host diskspace && flags="diskspace $flags"
checkflag $host decodingerr && flags="decodingerr $flags"
flags=$(echo "$flags" | sed -e "s/ $//")
n2reconf --file "/etc/n2/n2rxd.acked" --set "$host " "$host $exp $flags"

